version: '3.9'

services:
  frontend:
    build:
      context: ./
      dockerfile: DockerFile
    container_name: angular_frontend
    environment:
      - BACKEND_API_URL=http://localhost:8080
    ports:
      - "4200:80"
    networks:
      - ecomnetwork

networks:
  ecomnetwork:
    driver: bridge

